# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
NULL

read_file_cpp <- function(path) {
    .Call('_rePROBE_read_file_cpp', PACKAGE = 'rePROBE', path)
}

read_file_cpp2 <- function(path) {
    .Call('_rePROBE_read_file_cpp2', PACKAGE = 'rePROBE', path)
}

reversecomp <- function(x) {
    .Call('_rePROBE_reversecomp', PACKAGE = 'rePROBE', x)
}

prepare_vcf <- function(file_in, folder_out, fs = "/") {
    invisible(.Call('_rePROBE_prepare_vcf', PACKAGE = 'rePROBE', file_in, folder_out, fs))
}

get_fasta <- function(path, chrlist) {
    .Call('_rePROBE_get_fasta', PACKAGE = 'rePROBE', path, chrlist)
}

read_fasta <- function(path) {
    .Call('_rePROBE_read_fasta', PACKAGE = 'rePROBE', path)
}

